# -*- coding: utf-8 -*-
"""reto_7_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2zccBXY_pjtocuJcfImumTishxO5Sar
"""

i : int = 1
j : int = i*i
while i <= 100:
  print("Número: " +str(i)+ " con su cuadrado: " +str(j))
  i = i +1
  j = i*i
print("Hasta aqui van los 100 números")