# -*- coding: utf-8 -*-
"""Reto_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P_llf1K6EwYUi4Y5uW7pR13p8OfEACIm
"""

#PUNTO 1
i : int = 1
j : int = i*i
while i <= 100:
  print("Número: " +str(i)+ " con su cuadrado: " +str(j))
  i = i +1
  j = i*i
print("Hasta aqui van los 100 números")

#PUNTO 2
i : int = 0
while i <= 1000:
    i = i + 1
    if i % 2 !=0:
      continue
    print(i)

print("Hasta aqui van los pares")

i : int = 0
while i <= 1000:
  if i % 2 != 0:
    print(i)
  i = i + 1

print("Hasta aqui van los impares")

#PUNTO 3
numero = int(input("Ingrese un entero: "))
print("Los números pares menores o igual a " +str(numero)+ " son :" )
while numero >= 2:
  if numero % 2 == 0:
    print(numero)
  numero = numero - 1

#PUNTO 4
pais_A : int = 25000000
pais_B : int = 18900000
año_actual : int = 2022
while pais_A > pais_B:
  año_actual += 1
  pais_A = pais_A + pais_A*0.02
  pais_B = pais_B + pais_B*0.03
print("En el año " +str(año_actual)+ " la población del país B con un número de habitantes en ese año de " +str(pais_B)+ " millones de habitantes, supero al país A con ahora" +str(pais_A)+ " millones de habitantes")

#PUNTO 5
numero_factorial = int(input("Ingrese un entero: "))
numero_n : int = 1
factorial : int = 1
while numero_n <= numero_factorial and numero_factorial>0:
  factorial = factorial*numero_n
  numero_n += 1
print("El factorial de " +str(numero_factorial)+ " es " +str(factorial))

# PUNTO 6
import random
numero_ = int(input("Ingresa un entero entre uno y cien: "))
bandera : bool = True
minimo : int = 1
maximo : int = 100
while bandera == True:
  numero_secreto = random.randint(minimo, maximo)
  pregunta_ = input("Tu número es mayor, menor o igual a " +str(numero_secreto)+ ": ")
  if pregunta_ == "mayor":
    minimo = numero_secreto + 1
  elif pregunta_== "menor" :
    maximo = numero_secreto -1
  elif pregunta_ == "igual":
    break
print("El número en el que pensabas es: " +str(numero_secreto))

# PUNTO 7
numero_ = int (input("Ingrese un número entre 2 y 50 : "))
numero : int = 1
if 2 <= numero_ <= 50:
  print("Los divisores de " +str(numero_)+ " son:")
  while numero <= numero_:
    if numero_ % numero == 0:
      print(numero)
    numero= numero + 1
else:
  print("Perro es entre 2 y 50 loca")

# PUNTO 8
def numero_primo(numero: float, num_ : float, contador_ : float) -> float:
  while numero < 100 :
    numero = numero + 1
    num_ = 1
    contador_ = 0
    while  num_ <= (numero **0.5):
        if numero % num_ == 0:
          contador_ = contador_ + 1
        num_ = num_ + 1
    if contador_ == 1:
      print(numero)
  return "Estos fueron los primos"

if __name__ == "__main__":
  numero : float = 1
  num_ : float = 1
  contador_: float = 0
  num_primo = numero_primo(numero, num_ , contador_)
  print(num_primo)