# -*- coding: utf-8 -*-
"""reto_7_6

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2KQcQOQ_4cbBswEjEOfQ8bpzys0hbPx
"""

import random
numero_ = int(input("Ingresa un entero entre uno y cien: "))
bandera : bool = True
minimo : int = 1
maximo : int = 100
while bandera == True:
  numero_secreto = random.randint(minimo, maximo)
  pregunta_ = input("Tu número es mayor, menor o igual a " +str(numero_secreto)+ ": ")
  if pregunta_ == "mayor":
    minimo = numero_secreto + 1
  elif pregunta_== "menor" :
    maximo = numero_secreto -1
  elif pregunta_ == "igual":
    break
print("El número en el que pensabas es: " +str(numero_secreto))