# -*- coding: utf-8 -*-
"""reto_7_7

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18A13-CA_-79ASMQZGzKW10Lwi7Nzr9Ap
"""

numero_ = int (input("Ingrese un número entre 2 y 50 : "))
numero : int = 1
if 2 <= numero_ <= 50:
  print("Los divisores de " +str(numero_)+ " son:")
  while numero <= numero_:
    if numero_ % numero == 0:
      print(numero)
    numero= numero + 1
else:
  print("Perro es entre 2 y 50 loca")