# -*- coding: utf-8 -*-
"""reto_7_3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VSVlyn5OZ83IBXP8bU5zGGnqKanhkzlA
"""

numero = int(input("Ingrese un entero: "))
print("Los números pares menores o igual a " +str(numero)+ " son :" )
while numero >= 2:
  if numero % 2 == 0:
    print(numero)
  numero = numero - 1