# -*- coding: utf-8 -*-
"""reto_7_8

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ItUCALIBYDtHN2OjjXxQu-P7LwYhlyoy
"""

def numero_primo(numero: float, num_ : float, contador_ : float) -> float:
  while numero < 100 :
    numero = numero + 1
    num_ = 1
    contador_ = 0
    while  num_ <= (numero **0.5):
        if numero % num_ == 0:
          contador_ = contador_ + 1
        num_ = num_ + 1
    if contador_ == 1:
      print(numero)
  return "Estos fueron los primos"

if __name__ == "__main__":
  numero : float = 1
  num_ : float = 1
  contador_: float = 0
  num_primo = numero_primo(numero, num_ , contador_)
  print(num_primo)