# -*- coding: utf-8 -*-
"""reto_7_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MArmuVTcRVMGYV3BPvMDoX49pL_nEGLI
"""

pais_A : int = 25000000
pais_B : int = 18900000
año_actual : int = 2022
while pais_A > pais_B:
  año_actual += 1
  pais_A = pais_A + pais_A*0.02
  pais_B = pais_B + pais_B*0.03
print("En el año " +str(año_actual)+ " la población del país B con un número de habitantes en ese año de " +str(pais_B)+ " millones de habitantes, supero al país A con ahora" +str(pais_A)+ " millones de habitantes")