# -*- coding: utf-8 -*-
"""reto_7_2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HfFXh2uXjg1q1DAScuWMO_sNJEH5m2Ui
"""

i : int = 0
while i <= 1000:
    i = i + 1
    if i % 2 !=0:
      continue
    print(i)

print("Hasta aqui van los pares")

i : int = 0
while i <= 1000:
  if i % 2 != 0:
    print(i)
  i = i + 1

print("Hasta aqui van los impares")